version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: aster
      POSTGRES_PASSWORD: aster
      POSTGRES_DB: s3cretstash
    ports:
      - "5432:5432"
    volumes:
     - /postgres:/var/lib/postgresql/data
