from cryptography.fernet import Fernet

# This must be base64 and 32 bytes to work, at this moment generated by:
# dd if=/dev/urandom bs=32 count=1 2>/dev/null | openssl base64
MASTER_KEY = b"a61tB1Iiqz4YMI1i5+s9Q5S0S/UaRtgGAiX0TuRrEUk="

fernet = Fernet(MASTER_KEY)

